### ISSUE TITLE
Unable to create project through npx command

### ISSUE THREAD

**Issue by irufus** [storyblok/storyblok-create-demo#17]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template

When I try to go through the example provided in README.md I am unable to create a new project.

---

## Expected Behavior

Cloning of project:

## Current Behavior

```
Error: 'git clone' failed with status 1
    at ChildProcess.<anonymous> (C:\Users\Ishmael\AppData\Local\npm-cache\_npx\6d8011074524d37e\node_modules\@storyblok\create-demo\src\clone.js:40:16)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:673:12)
    Error: ENOENT: no such file or directory, stat './demo'
    Code: ENOENT
```

## Steps to Reproduce

Take the following steps in PowerShell on Windows 10 with Node version 14.15

1. `npx @storyblok/create-demo@latest`
2. Provide your key from app.storyblok
3. Provide the region your project is configured

**Comment by irufus** [comment]
So I ran the installation again on a different computer that is running Node version 18. I will try to upgrade first and see if I can reproduce.

**Comment by roberto-butti** [comment]
Ok so I can close the issue. If you have an issue on another platform, let me know the version of the node, the operating system, and if `git` is installed. In future releases, I will add some checks on the requirements of the environment.
