### ISSUE TITLE
[Remix] storyblokInit not working if it loads from server side

### ISSUE THREAD

**Issue by anakinsolo** [storyblok/storyblok-create-demo#18]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template
I want to move the storyblok accesstoken from the hardcoded value in app/root.jsx or app/root.tsx to .env, and access it by using for example `process.env.TOKEN`

The thing is, it doesn't work
![image](https://user-images.githubusercontent.com/8152024/223857763-364f2dc4-5181-42d9-a583-987ae783474f.png)

My app.jsx
```
import { storyblokInit, apiPlugin } from "@storyblok/react";
import Feature from "./components/Feature";
import Grid from "./components/Grid";
import Page from "./components/Page";
import Teaser from "./components/Teaser";

const components = {
  feature: Feature,
  grid: Grid,
  teaser: Teaser,
  page: Page,
};

const accessToken = process.env.TOKEN;

storyblokInit({
  accessToken,
  use: [apiPlugin],
  components,
});

```
My .env file
```
TOKEN=MYTOKEN
```
My files structure
![image](https://user-images.githubusercontent.com/8152024/223858214-00559bb1-172e-404a-b483-5f9011e4e11a.png)

---

## Expected Behavior

I expect the token should be read from .env file

## Current Behavior

Token seems to be empty/null/undefined, basically it cannot be read unless you hardcode it

## Steps to Reproduce
Very basic steps

1. `npx @storyblok/create-demo@latest`
2. Follow the promts, choose remix
3. cd to the newly-created folder, `npm i`, `npm run dev`
4. Move the hardcoded accessToken to a .env file in the root folder
5. Go to localhost:3000 and see the error messages there and in terminal.

Here is the picture
![image](https://user-images.githubusercontent.com/8152024/223858575-b48dd251-78a0-4606-8621-b751df140ac4.png)

**Comment by roberto-butti** [comment]
The Storyblok Create Demo aims to create a very basic template with the logic for integrating the front end with Storyblok. Starting from the demo created by Storyblok Create Demo, you can refactor and customize the code. I totally agree that storing some configuration variables in a centralized place like, for example, the .env file or in environment variables is a good practice.
Specifically for Remix, this is the Remix doc to manage the env vars in the right way: https://remix.run/docs/en/main/guides/envvars

Another article on this topic is: https://makerkit.dev/blog/tutorials/environment-variables-remix
